# Generated by Django 5.2 on 2025-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarroEstacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('nome_motorista', models.CharField(max_length=100)),
                ('numero_contato', models.CharField(max_length=15)),
                ('hora_estacionado', models.DateTimeField(auto_now_add=True)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
