# Generated by Django 5.1.2 on 2026-05-12 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável'),
        ),
    ]
