# Generated by Django 5.1.2 on 2025-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_veiculo_delete_carroestacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='avarias',
            field=models.TextField(blank=True),
        ),
    ]
